name: Reddit Check
on: workflow_dispatch

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Install Playwright with browsers
        run: |
          npm install
          npx playwright install --with-deps chromium
      
      - name: Run test
        run: |
          npx playwright test tests/redd-pop.test.js \
            --project=chromium \
            --timeout=60000
